### ISSUE TITLE
License

### ISSUE THREAD

**Issue by LeonG-ZA** [jratcliff63367/oldsource#2]
Hi,

In the Readme it mentions that: "As per the agreement you should have signed, this source code is to be used
by The Audio Solution DigPak licensees for maintenence purposes ONLY!"  
Is this still true? If not, what kind of license does the code fall under?

Kind Regards,
Leon

**Comment by jratcliff63367** [comment]
No. That's super old.

**Comment by volkertb** [comment]
Maybe this can be clarified in a LICENSE file?

**Comment by jratcliff63367** [comment]
I only uploaded this because someone asked for a copy. I can't believe
anyone would use it or find it useful. But, yes, when I have some time I
can change the license on it.

**Comment by volkertb** [comment]
Actually, you'd be surprised how lively the retro DOS coder community is these days. :)

Nostalgia is a strong thing for many people. Also, don't underestimate the historic value of your work. You are considered one of the pioneers in the history of PC audio.

Thanks for uploading this.

**Comment by volkertb** [comment]
Since the new license of the code has been clarified in commit 0b687b2e0c0010265015acc6fa1f149a79ee113a, this issue can be closed.
