### ISSUE TITLE
Can this repository be renamed to `DIGPAK`?

### ISSUE THREAD

**Issue by volkertb** [jratcliff63367/oldsource#3]
`oldsource` is a bit ambiguous.

Also, maybe you can enable [GitHub Discussions](https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository) for this project?

Thanks. :slightly_smiling_face:

**Comment by MobyGamer** [comment]
John did this as a favor and certainly doesn't want to maintain the code or repo (nor do I blame him).  I think it would be best to fork this project to get the name and features you want.

**Comment by jratcliff63367** [comment]
It's a fair point. But I doubt a depot can be renamed. I would have to delete this one and create a new one. The reason it is called 'old source' is because someone on the internets asked me for a copy of my old code. I had no idea anyone else would even look at it.

If it can be renamed, I will do so, but I suspect that isn't possible.

**Comment by andrewbird** [comment]
Hello, yes it can be renamed and github will fixup others' references to be forwarded to the new name. Here's what Github has to say on the matter https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

**Comment by volkertb** [comment]
@MobyGamer You make a good point. It's not my intention to burden John with any further maintenance of this project. Since he added me as a Contributor for this repo, I can approve and merge pull requests, and basically manage this repo going forward. Renaming the repo and enabling GitHub Discussions are among the few things that only the repo owner can actually do.

But perhaps it would indeed be better to consider this the "historic" release repo, and have any new development (including discussions) take place in forks.

Anyway, I see the repository was successfully renamed. So I'll close this issue.

Thanks! :+1:
